version: "2.1"
services:
  podgrab:
    build:
      context: .
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=3600
      - PASSWORD=podgrab
    volumes:
      - ./config:/config
      - ./assets:/assets
    ports:
      - 8080:8080
    restart: unless-stopped
